# EDA

In [1]:
import numpy as np

Смещенные стандартное отклонение и дисперсия

In [2]:
x = np.array([167, 181, 174, 178, 175, 164, 182, 178, 193, 166, 154, 170, 177])
x

array([167, 181, 174, 178, 175, 164, 182, 178, 193, 166, 154, 170, 177])

In [11]:
np.std(x) # standard deviation


9.382092977531892

In [12]:
np.var(x) # dispersion 

88.02366863905326

In [6]:
np.sqrt(88.02366863905326)

9.382092977531892

Несмещенные стандартное отклонение и дисперсия

In [7]:
x = np.array([167, 181, 174, 178, 175, 164, 182, 178, 193, 166, 154, 170, 177])
x

array([167, 181, 174, 178, 175, 164, 182, 178, 193, 166, 154, 170, 177])

In [13]:
np.std(x, ddof=1) # ddof - степени свободы

9.765191977579056

In [9]:
np.var(x, ddof=1)

95.35897435897436

In [10]:
np.sqrt(95.35897435897436)

9.765191977579056

Медиана

In [14]:
z = np.array([100, 80, 75, 77, 89, 33, 45, 25, 65, 17, 30, 24, 57, 55, 70, 75, 65, 84, 90, 150])
z

array([100,  80,  75,  77,  89,  33,  45,  25,  65,  17,  30,  24,  57,
        55,  70,  75,  65,  84,  90, 150])

In [15]:
z.shape

(20,)

In [17]:
z.sort()
z

array([ 17,  24,  25,  30,  33,  45,  55,  57,  65,  65,  70,  75,  75,
        77,  80,  84,  89,  90, 100, 150])

In [18]:
(z[9] + z[10])/2

67.5

Квантили

In [19]:
z = np.array([1, 2, 4, 2, 1, 5, 7, 2, 3, 5, 7, 8, 9])
z

array([1, 2, 4, 2, 1, 5, 7, 2, 3, 5, 7, 8, 9])

In [20]:
z.sort()
z

array([1, 1, 2, 2, 2, 3, 4, 5, 5, 7, 7, 8, 9])

если  n k/100 целое число, то k-я персентиль - это среднее значение элементов под номерами nk/100 и nk/100+1

Если n k/100 не целое число, то k-я персентиль совпадает с измерением j+1, где j - максимальное число, которое меньше, чем n k/100

In [21]:
n = len(z)
n

13

In [22]:
k = 25
n*k/100

3.25

In [23]:
3+1

4

In [25]:
z[3] # element for 25-%

2

In [26]:
k = 75
n*k/100

9.75

In [27]:
9+1

10

In [29]:
z[9] # element of 75-%

7